# Generated by Django 5.0.1 on 2024-01-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='name',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
